project:
  type: website
  output-dir: docs

website:
  title: "R in the browser"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: web-r.qmd
        text: WebR
      - href: shinylive.qmd
        text: shinylive
    tools:
      - href: https://github.com/paulc91/rinthebrowser
        icon: "github"

resources: 
  - "webr-serviceworker.js"
  - "webr-worker.js"
  - "shinylive-sw.js"
